"""control

Revision ID: 324cd3d21a18
Revises: 
Create Date: 2023-06-06 15:48:37.318058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '324cd3d21a18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_recents')
    op.drop_table('detection_reports')
    with op.batch_alter_table('detection_routes', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)

    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)

    with op.batch_alter_table('layer_coordinates', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)

    with op.batch_alter_table('markers', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)

    with op.batch_alter_table('media_sources', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)

    with op.batch_alter_table('message_to_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('message_to_list_messege_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'messages', ['message_id'], ['id'])
        batch_op.drop_column('messege_id')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_from', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('original_message_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('messages_orginal_message_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('messages_messege_from_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'messages', ['original_message_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['message_from'], ['id'])
        batch_op.drop_column('messege_from')
        batch_op.drop_column('orginal_message_id')

    with op.batch_alter_table('screen_shots', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screen_shots', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orginal_message_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('messege_from', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('messages_messege_from_fkey', 'users', ['messege_from'], ['id'])
        batch_op.create_foreign_key('messages_orginal_message_id_fkey', 'messages', ['orginal_message_id'], ['id'])
        batch_op.drop_column('original_message_id')
        batch_op.drop_column('message_from')

    with op.batch_alter_table('message_to_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('messege_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('message_to_list_messege_id_fkey', 'messages', ['messege_id'], ['id'])
        batch_op.drop_column('message_id')

    with op.batch_alter_table('media_sources', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('markers', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('layer_coordinates', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('detection_routes', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)

    op.create_table('detection_reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('header', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('format', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('create_at', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('update_at', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('delete_at', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('create_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('update_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('delete_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='detection_reports_pkey'),
    sa.UniqueConstraint('name', name='detection_reports_name_key')
    )
    op.create_table('user_recents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('create_at', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('update_at', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('delete_at', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('create_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('update_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('delete_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_recents_pkey')
    )
    # ### end Alembic commands ###
