"""empty message

Revision ID: 702e6481c425
Revises: 0e79e16e5cb1
Create Date: 2023-05-29 15:50:40.063920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '702e6481c425'
down_revision = '0e79e16e5cb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serkan', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('serkan')

    # ### end Alembic commands ###
