"""control

Revision ID: 8057b86b1f3d
Revises: eeb569584c60
Create Date: 2023-06-08 11:39:00.876743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8057b86b1f3d'
down_revision = 'eeb569584c60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detection_routes', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)

    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)

    with op.batch_alter_table('layer_coordinates', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)

    with op.batch_alter_table('markers', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)

    with op.batch_alter_table('media_sources', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)

    with op.batch_alter_table('screen_shots', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)

    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sensor_weight', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('unity_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sensor_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('evaluation_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rpm', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('detection_range', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_fusible', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cake_slice', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('line_of_sight_angle', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('line_of_sight_distance', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('near_circle', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('circle_radius', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('circle_time_interval', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_meteorology_includes', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('desired_columns', sa.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('models', sa.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('filters', sa.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('training_config', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('nvr', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'unities', ['unity_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('nvr')
        batch_op.drop_column('is_approved')
        batch_op.drop_column('image')
        batch_op.drop_column('training_config')
        batch_op.drop_column('filters')
        batch_op.drop_column('models')
        batch_op.drop_column('desired_columns')
        batch_op.drop_column('is_meteorology_includes')
        batch_op.drop_column('circle_time_interval')
        batch_op.drop_column('circle_radius')
        batch_op.drop_column('near_circle')
        batch_op.drop_column('line_of_sight_distance')
        batch_op.drop_column('line_of_sight_angle')
        batch_op.drop_column('cake_slice')
        batch_op.drop_column('is_fusible')
        batch_op.drop_column('detection_range')
        batch_op.drop_column('rpm')
        batch_op.drop_column('evaluation_number')
        batch_op.drop_column('sensor_type')
        batch_op.drop_column('unity_id')
        batch_op.drop_column('sensor_weight')

    with op.batch_alter_table('screen_shots', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('media_sources', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('markers', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('layer_coordinates', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('detection_routes', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
