"""empty message

Revision ID: 8d861859c9fc
Revises: e81434cb9c9c
Create Date: 2023-06-03 13:46:52.444258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d861859c9fc'
down_revision = 'e81434cb9c9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authorities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('create_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_by', sa.Integer(), nullable=True))

    with op.batch_alter_table('authority_packs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('create_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_by', sa.Integer(), nullable=True))

    with op.batch_alter_table('command_collar_mark_rakss', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('create_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_by', sa.Integer(), nullable=True))

    with op.batch_alter_table('command_collar_marks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('create_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_by', sa.Integer(), nullable=True))

    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('create_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_by', sa.Integer(), nullable=True))

    with op.batch_alter_table('data_packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('create_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_by', sa.Integer(), nullable=True))

    with op.batch_alter_table('detection_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('create_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_by', sa.Integer(), nullable=True))

    with op.batch_alter_table('detection_routes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('create_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_by', sa.Integer(), nullable=True))

    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('create_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_by', sa.Integer(), nullable=True))

    with op.batch_alter_table('hierarchies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('create_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_by', sa.Integer(), nullable=True))

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    with op.batch_alter_table('kogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('create_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_by', sa.Integer(), nullable=True))

    with op.batch_alter_table('layer_coordinates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('create_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_by', sa.Integer(), nullable=True))
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)

    with op.batch_alter_table('layers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('create_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_by', sa.Integer(), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    with op.batch_alter_table('maps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('create_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_by', sa.Integer(), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    with op.batch_alter_table('markers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('create_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_by', sa.Integer(), nullable=True))

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('create_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_by', sa.Integer(), nullable=True))

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('create_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_by', sa.Integer(), nullable=True))

    with op.batch_alter_table('message_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('create_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_by', sa.Integer(), nullable=True))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('create_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_by', sa.Integer(), nullable=True))

    with op.batch_alter_table('preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('create_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_by', sa.Integer(), nullable=True))

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('create_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_by', sa.Integer(), nullable=True))

    with op.batch_alter_table('screen_shots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('create_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_by', sa.Integer(), nullable=True))

    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('create_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_by', sa.Integer(), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    with op.batch_alter_table('symbols', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('create_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_by', sa.Integer(), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    with op.batch_alter_table('unities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('create_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_by', sa.Integer(), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    with op.batch_alter_table('user_authorities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('create_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_by', sa.Integer(), nullable=True))

    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('create_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_by', sa.Integer(), nullable=True))

    with op.batch_alter_table('user_recents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('create_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_by', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_login_ip', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login_ip')
        batch_op.drop_column('last_login')
        batch_op.drop_column('delete_by')
        batch_op.drop_column('update_by')
        batch_op.drop_column('create_by')

    with op.batch_alter_table('user_recents', schema=None) as batch_op:
        batch_op.drop_column('delete_by')
        batch_op.drop_column('update_by')
        batch_op.drop_column('create_by')
        batch_op.drop_column('active')
        batch_op.drop_column('delete_at')
        batch_op.drop_column('update_at')
        batch_op.drop_column('create_at')

    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_column('delete_by')
        batch_op.drop_column('update_by')
        batch_op.drop_column('create_by')
        batch_op.drop_column('active')
        batch_op.drop_column('delete_at')
        batch_op.drop_column('update_at')
        batch_op.drop_column('create_at')

    with op.batch_alter_table('user_authorities', schema=None) as batch_op:
        batch_op.drop_column('delete_by')
        batch_op.drop_column('update_by')
        batch_op.drop_column('create_by')
        batch_op.drop_column('active')
        batch_op.drop_column('delete_at')
        batch_op.drop_column('update_at')
        batch_op.drop_column('create_at')

    with op.batch_alter_table('unities', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.drop_column('delete_by')
        batch_op.drop_column('update_by')
        batch_op.drop_column('create_by')
        batch_op.drop_column('active')
        batch_op.drop_column('delete_at')
        batch_op.drop_column('update_at')
        batch_op.drop_column('create_at')

    with op.batch_alter_table('symbols', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.drop_column('delete_by')
        batch_op.drop_column('update_by')
        batch_op.drop_column('create_by')
        batch_op.drop_column('active')
        batch_op.drop_column('delete_at')
        batch_op.drop_column('update_at')
        batch_op.drop_column('create_at')

    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.drop_column('delete_by')
        batch_op.drop_column('update_by')
        batch_op.drop_column('create_by')
        batch_op.drop_column('active')
        batch_op.drop_column('delete_at')
        batch_op.drop_column('update_at')
        batch_op.drop_column('create_at')

    with op.batch_alter_table('screen_shots', schema=None) as batch_op:
        batch_op.drop_column('delete_by')
        batch_op.drop_column('update_by')
        batch_op.drop_column('create_by')
        batch_op.drop_column('active')
        batch_op.drop_column('delete_at')
        batch_op.drop_column('update_at')
        batch_op.drop_column('create_at')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('delete_by')
        batch_op.drop_column('update_by')
        batch_op.drop_column('create_by')
        batch_op.drop_column('active')
        batch_op.drop_column('delete_at')
        batch_op.drop_column('update_at')
        batch_op.drop_column('create_at')

    with op.batch_alter_table('preferences', schema=None) as batch_op:
        batch_op.drop_column('delete_by')
        batch_op.drop_column('update_by')
        batch_op.drop_column('create_by')
        batch_op.drop_column('active')
        batch_op.drop_column('delete_at')
        batch_op.drop_column('update_at')
        batch_op.drop_column('create_at')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('delete_by')
        batch_op.drop_column('update_by')
        batch_op.drop_column('create_by')
        batch_op.drop_column('active')
        batch_op.drop_column('delete_at')
        batch_op.drop_column('update_at')
        batch_op.drop_column('create_at')

    with op.batch_alter_table('message_templates', schema=None) as batch_op:
        batch_op.drop_column('delete_by')
        batch_op.drop_column('update_by')
        batch_op.drop_column('create_by')
        batch_op.drop_column('active')
        batch_op.drop_column('delete_at')
        batch_op.drop_column('update_at')
        batch_op.drop_column('create_at')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('delete_by')
        batch_op.drop_column('update_by')
        batch_op.drop_column('create_by')
        batch_op.drop_column('active')
        batch_op.drop_column('delete_at')
        batch_op.drop_column('update_at')
        batch_op.drop_column('create_at')

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_column('delete_by')
        batch_op.drop_column('update_by')
        batch_op.drop_column('create_by')
        batch_op.drop_column('active')
        batch_op.drop_column('delete_at')
        batch_op.drop_column('update_at')
        batch_op.drop_column('create_at')

    with op.batch_alter_table('markers', schema=None) as batch_op:
        batch_op.drop_column('delete_by')
        batch_op.drop_column('update_by')
        batch_op.drop_column('create_by')
        batch_op.drop_column('active')
        batch_op.drop_column('delete_at')
        batch_op.drop_column('update_at')
        batch_op.drop_column('create_at')

    with op.batch_alter_table('maps', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.drop_column('delete_by')
        batch_op.drop_column('update_by')
        batch_op.drop_column('create_by')
        batch_op.drop_column('active')
        batch_op.drop_column('delete_at')
        batch_op.drop_column('update_at')
        batch_op.drop_column('create_at')

    with op.batch_alter_table('layers', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.drop_column('delete_by')
        batch_op.drop_column('update_by')
        batch_op.drop_column('create_by')
        batch_op.drop_column('active')
        batch_op.drop_column('delete_at')
        batch_op.drop_column('update_at')
        batch_op.drop_column('create_at')

    with op.batch_alter_table('layer_coordinates', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.drop_column('delete_by')
        batch_op.drop_column('update_by')
        batch_op.drop_column('create_by')
        batch_op.drop_column('active')
        batch_op.drop_column('delete_at')
        batch_op.drop_column('update_at')
        batch_op.drop_column('create_at')

    with op.batch_alter_table('kogs', schema=None) as batch_op:
        batch_op.drop_column('delete_by')
        batch_op.drop_column('update_by')
        batch_op.drop_column('create_by')
        batch_op.drop_column('active')
        batch_op.drop_column('delete_at')
        batch_op.drop_column('update_at')
        batch_op.drop_column('create_at')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('hierarchies', schema=None) as batch_op:
        batch_op.drop_column('delete_by')
        batch_op.drop_column('update_by')
        batch_op.drop_column('create_by')
        batch_op.drop_column('active')
        batch_op.drop_column('delete_at')
        batch_op.drop_column('update_at')
        batch_op.drop_column('create_at')

    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.drop_column('delete_by')
        batch_op.drop_column('update_by')
        batch_op.drop_column('create_by')
        batch_op.drop_column('active')
        batch_op.drop_column('delete_at')
        batch_op.drop_column('update_at')
        batch_op.drop_column('create_at')

    with op.batch_alter_table('detection_routes', schema=None) as batch_op:
        batch_op.drop_column('delete_by')
        batch_op.drop_column('update_by')
        batch_op.drop_column('create_by')
        batch_op.drop_column('active')
        batch_op.drop_column('delete_at')
        batch_op.drop_column('update_at')
        batch_op.drop_column('create_at')

    with op.batch_alter_table('detection_reports', schema=None) as batch_op:
        batch_op.drop_column('delete_by')
        batch_op.drop_column('update_by')
        batch_op.drop_column('create_by')
        batch_op.drop_column('active')
        batch_op.drop_column('delete_at')
        batch_op.drop_column('update_at')
        batch_op.drop_column('create_at')

    with op.batch_alter_table('data_packages', schema=None) as batch_op:
        batch_op.drop_column('delete_by')
        batch_op.drop_column('update_by')
        batch_op.drop_column('create_by')
        batch_op.drop_column('active')
        batch_op.drop_column('delete_at')
        batch_op.drop_column('update_at')
        batch_op.drop_column('create_at')

    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.drop_column('delete_by')
        batch_op.drop_column('update_by')
        batch_op.drop_column('create_by')
        batch_op.drop_column('active')
        batch_op.drop_column('delete_at')
        batch_op.drop_column('update_at')
        batch_op.drop_column('create_at')

    with op.batch_alter_table('command_collar_marks', schema=None) as batch_op:
        batch_op.drop_column('delete_by')
        batch_op.drop_column('update_by')
        batch_op.drop_column('create_by')
        batch_op.drop_column('active')
        batch_op.drop_column('delete_at')
        batch_op.drop_column('update_at')
        batch_op.drop_column('create_at')

    with op.batch_alter_table('command_collar_mark_rakss', schema=None) as batch_op:
        batch_op.drop_column('delete_by')
        batch_op.drop_column('update_by')
        batch_op.drop_column('create_by')
        batch_op.drop_column('active')
        batch_op.drop_column('delete_at')
        batch_op.drop_column('update_at')
        batch_op.drop_column('create_at')

    with op.batch_alter_table('authority_packs', schema=None) as batch_op:
        batch_op.drop_column('delete_by')
        batch_op.drop_column('update_by')
        batch_op.drop_column('create_by')
        batch_op.drop_column('active')
        batch_op.drop_column('delete_at')
        batch_op.drop_column('update_at')
        batch_op.drop_column('create_at')

    with op.batch_alter_table('authorities', schema=None) as batch_op:
        batch_op.drop_column('delete_by')
        batch_op.drop_column('update_by')
        batch_op.drop_column('create_by')
        batch_op.drop_column('active')
        batch_op.drop_column('delete_at')
        batch_op.drop_column('update_at')
        batch_op.drop_column('create_at')

    # ### end Alembic commands ###
