"""empty message

Revision ID: fc142f39b460
Revises: 
Create Date: 2023-06-19 12:58:08.936433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc142f39b460'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anomalies', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)

    with op.batch_alter_table('anomaly_routes', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)

    with op.batch_alter_table('area_coordinates', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)

    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(precision=5), nullable=False))
        batch_op.add_column(sa.Column('longitude', sa.Float(precision=5), nullable=False))

    with op.batch_alter_table('markers', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)

    with op.batch_alter_table('media_sources', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)

    with op.batch_alter_table('screen_shots', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)

    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)

    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('screen_shots', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('media_sources', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('markers', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    with op.batch_alter_table('area_coordinates', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('anomaly_routes', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('anomalies', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
